/*  This program calculates the amount of profit generated by stadium seating at a softball game. 
    It take inputs of the amount of tickets sold for A, B, and C seating sections. The program
    then outputs the total calculated profit, in USD.   */

#include<iostream>
#include<iomanip>

using namespace std;

int main() 
{

    int aTicketsSold, bTicketsSold, cTicketsSold;
    float classACost = 15, classBCost = 12, classCCost = 9, ticketProfit;

    cout << "Enter amount of Class A tickets sold: ";
    cin >> aTicketsSold;
    cout << endl;

    cout << "Enter amount of Class B tickets sold: ";
    cin >> bTicketsSold;
    cout << endl;
    
    cout << "Enter amount of Class C tickets sold: ";
    cin >> cTicketsSold;
    cout << endl;
    
    // Sum of tickets sold multiplied by their respective prices 
    ticketProfit = (classACost * aTicketsSold) + 
        (classBCost * bTicketsSold) + (classCCost * cTicketsSold);

    // since ticketProfit is a float, the decimal points will be displayed
    cout << fixed << setprecision(2);
    
    cout << "A $" << ticketProfit << " profit was made from class a, b, and c seats." << endl;

    return 0;

}